spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:seapp;
    username: sa
    password:


sample:
  search:
    client:
      kakao:
        api-key: af046e9a2137007492338aeaed6943c4
        admin-key : df8e86d8acb3e22a8a6fad562c39ed83
      naver:
        client-key: lTeV59VHOcfwRnKp7rBA
        client-secret: CepaA1fyRF